//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFeRecepcaoEvento
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRecepcaoEvento4", ConfigurationName="NFeRecepcaoEvento.NFeRecepcaoEvento4Soap")]
    public interface NFeRecepcaoEvento4Soap
    {
        
        // CODEGEN: Gerando contrato de mensagem porque a operação nfeRecepcaoEventoNF não é RPC nem documento encapsulado.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRecepcaoEvento4/nfeRecepcaoEventoNF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NFeRecepcaoEvento.nfeRecepcaoEventoNFResponse nfeRecepcaoEventoNF(NFeRecepcaoEvento.nfeRecepcaoEventoNFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRecepcaoEvento4/nfeRecepcaoEventoNF", ReplyAction="*")]
        System.Threading.Tasks.Task<NFeRecepcaoEvento.nfeRecepcaoEventoNFResponse> nfeRecepcaoEventoNFAsync(NFeRecepcaoEvento.nfeRecepcaoEventoNFRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeRecepcaoEventoNFRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRecepcaoEvento4", Order=0)]
        public System.Xml.XmlNode nfeDadosMsg;
        
        public nfeRecepcaoEventoNFRequest()
        {
        }
        
        public nfeRecepcaoEventoNFRequest(System.Xml.XmlNode nfeDadosMsg)
        {
            this.nfeDadosMsg = nfeDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeRecepcaoEventoNFResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRecepcaoEvento4", Order=0)]
        public System.Xml.XmlNode nfeRecepcaoEventoNFResult;
        
        public nfeRecepcaoEventoNFResponse()
        {
        }
        
        public nfeRecepcaoEventoNFResponse(System.Xml.XmlNode nfeRecepcaoEventoNFResult)
        {
            this.nfeRecepcaoEventoNFResult = nfeRecepcaoEventoNFResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface NFeRecepcaoEvento4SoapChannel : NFeRecepcaoEvento.NFeRecepcaoEvento4Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class NFeRecepcaoEvento4SoapClient : System.ServiceModel.ClientBase<NFeRecepcaoEvento.NFeRecepcaoEvento4Soap>, NFeRecepcaoEvento.NFeRecepcaoEvento4Soap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public NFeRecepcaoEvento4SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(NFeRecepcaoEvento4SoapClient.GetBindingForEndpoint(endpointConfiguration), NFeRecepcaoEvento4SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NFeRecepcaoEvento4SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(NFeRecepcaoEvento4SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NFeRecepcaoEvento4SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(NFeRecepcaoEvento4SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NFeRecepcaoEvento4SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFeRecepcaoEvento.nfeRecepcaoEventoNFResponse NFeRecepcaoEvento.NFeRecepcaoEvento4Soap.nfeRecepcaoEventoNF(NFeRecepcaoEvento.nfeRecepcaoEventoNFRequest request)
        {
            return base.Channel.nfeRecepcaoEventoNF(request);
        }
        
        public System.Xml.XmlNode nfeRecepcaoEventoNF(System.Xml.XmlNode nfeDadosMsg)
        {
            NFeRecepcaoEvento.nfeRecepcaoEventoNFRequest inValue = new NFeRecepcaoEvento.nfeRecepcaoEventoNFRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            NFeRecepcaoEvento.nfeRecepcaoEventoNFResponse retVal = ((NFeRecepcaoEvento.NFeRecepcaoEvento4Soap)(this)).nfeRecepcaoEventoNF(inValue);
            return retVal.nfeRecepcaoEventoNFResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFeRecepcaoEvento.nfeRecepcaoEventoNFResponse> NFeRecepcaoEvento.NFeRecepcaoEvento4Soap.nfeRecepcaoEventoNFAsync(NFeRecepcaoEvento.nfeRecepcaoEventoNFRequest request)
        {
            return base.Channel.nfeRecepcaoEventoNFAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFeRecepcaoEvento.nfeRecepcaoEventoNFResponse> nfeRecepcaoEventoNFAsync(System.Xml.XmlNode nfeDadosMsg)
        {
            NFeRecepcaoEvento.nfeRecepcaoEventoNFRequest inValue = new NFeRecepcaoEvento.nfeRecepcaoEventoNFRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            return ((NFeRecepcaoEvento.NFeRecepcaoEvento4Soap)(this)).nfeRecepcaoEventoNFAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NFeRecepcaoEvento4Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.NFeRecepcaoEvento4Soap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NFeRecepcaoEvento4Soap))
            {
                return new System.ServiceModel.EndpointAddress("https://www.nfe.fazenda.gov.br/NFeRecepcaoEvento4/NFeRecepcaoEvento4.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.NFeRecepcaoEvento4Soap12))
            {
                return new System.ServiceModel.EndpointAddress("https://www.nfe.fazenda.gov.br/NFeRecepcaoEvento4/NFeRecepcaoEvento4.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            NFeRecepcaoEvento4Soap,
            
            NFeRecepcaoEvento4Soap12,
        }
    }
}
